################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/StepMotorLib.c \
../Core/Src/StepMotorParams.c \
../Core/Src/axis.c \
../Core/Src/dma.c \
../Core/Src/gpio.c \
../Core/Src/main.c \
../Core/Src/mfgcode_uart.c \
../Core/Src/stm32f0xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/sysmem.c \
../Core/Src/system_stm32f0xx.c \
../Core/Src/tim.c \
../Core/Src/usart.c 

OBJS += \
./Core/Src/StepMotorLib.o \
./Core/Src/StepMotorParams.o \
./Core/Src/axis.o \
./Core/Src/dma.o \
./Core/Src/gpio.o \
./Core/Src/main.o \
./Core/Src/mfgcode_uart.o \
./Core/Src/stm32f0xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/sysmem.o \
./Core/Src/system_stm32f0xx.o \
./Core/Src/tim.o \
./Core/Src/usart.o 

C_DEPS += \
./Core/Src/StepMotorLib.d \
./Core/Src/StepMotorParams.d \
./Core/Src/axis.d \
./Core/Src/dma.d \
./Core/Src/gpio.d \
./Core/Src/main.d \
./Core/Src/mfgcode_uart.d \
./Core/Src/stm32f0xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/sysmem.d \
./Core/Src/system_stm32f0xx.d \
./Core/Src/tim.d \
./Core/Src/usart.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/StepMotorLib.o: ../Core/Src/StepMotorLib.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/StepMotorLib.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/StepMotorParams.o: ../Core/Src/StepMotorParams.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/StepMotorParams.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/axis.o: ../Core/Src/axis.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/axis.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/dma.o: ../Core/Src/dma.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/dma.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/gpio.o: ../Core/Src/gpio.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/main.o: ../Core/Src/main.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/mfgcode_uart.o: ../Core/Src/mfgcode_uart.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/mfgcode_uart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/stm32f0xx_it.o: ../Core/Src/stm32f0xx_it.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f0xx_it.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/sysmem.o: ../Core/Src/sysmem.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/system_stm32f0xx.o: ../Core/Src/system_stm32f0xx.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32f0xx.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/tim.o: ../Core/Src/tim.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/tim.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/usart.o: ../Core/Src/usart.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER '-DHSE_VALUE=8000000' '-DHSE_STARTUP_TIMEOUT=100' '-DLSE_STARTUP_TIMEOUT=5000' '-DLSE_VALUE=32768' '-DHSI_VALUE=8000000' '-DLSI_VALUE=40000' '-DVDD_VALUE=3300' '-DPREFETCH_ENABLE=1' '-DINSTRUCTION_CACHE_ENABLE=0' '-DDATA_CACHE_ENABLE=0' -DSTM32F051x8 -c -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/Device/ST/STM32F0xx/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/STM32F0xx_HAL_Driver/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Core/Inc -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/RTOS2/Include -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/DSP/Include -I"/home/tester/Documents/GitHub/MicroFlex/stm32/StepMotor/Drivers/CMSIS" -I/home/arpoyda/STM32CubeIDE/RoboArm/StepMotor/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/usart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

